name: CI
      
# Controls when the workflow will run. 
on:

  # Triggers the workflow on push or pull request events, but only for the master branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # This allows the workflow run to be run manually from the Actions tab in GitHub.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:

  # Run the GUI Layout Toolbox tests in the Java desktop environment.
  run-tests:

    # Define the job strategy.
    strategy:

      # Set up the job strategy matrix to define the different job configurations.
      matrix:
        
        # List of operating systems to run the tests on.
        os: [ ubuntu-latest ]

        # List of MATLAB releases over which to run the tests.
        matlab-version: [ R2023b ]

        # MATLAB startup options (none or the JavaScript Desktop (-webui)).
        matlab-startup-options: [ '', -webui ]
    
    # Specify the runner that the job will run on.
    runs-on: ${{ matrix.os }}

    # Don't fail the entire run if one job fails.
    continue-on-error: true

    # Steps define a sequence of tasks to be executed as part of the job.
    steps:
      
      # Check out the repository under $GITHUB_WORKSPACE, so that the job can access it.
      - name: Check out the repository
        uses: actions/checkout@v4

      # Start the display server on the runner.
      - name: Start display server       
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
          
      # Set up MATLAB on the runner.
      - name: Set up MATLAB on the runner
        uses: matlab-actions/setup-matlab@v2-rc
        with:          
          release: ${{ matrix.matlab-version }}

      # Run the GLT tests.
      - name: Run tests
        uses: matlab-actions/run-command@v1
        with:
          startup-options: ${{ matrix.matlab-startup-options }}
          command: |
            disp hasDisplay
            matlab.ui.internal.hasDisplay
            disp isFigureShowEnabled
            matlab.ui.internal.isFigureShowEnabled
